### ISSUE TITLE
Ingestion issue

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#121]
The bug happend with files having the following resfDecl : 

```xml
         <refsDecl n="CTS"><cRefPattern n="unknown" matchPattern="(\w+)" replacementPattern="#xpath(tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])"><p>This pointer pattern extracts unknown</p></cRefPattern></refsDecl>
```

and the content I attached

```pyerror
>>> Starting tests !
>>> Files to test : 540
...............................................................................................................................................................................................................................................................................................................................................
All Metadata Files Passed
XXmultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/HookTest/test.py", line 376, in unit
    for name, status, unitlogs in unit.test(self.scheme, self.inventory):
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/HookTest/capitains_units/cts.py", line 636, in test
    status = False not in [status for status in getattr(self, test)()]
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/HookTest/capitains_units/cts.py", line 636, in <listcomp>
    status = False not in [status for status in getattr(self, test)()]
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/HookTest/capitains_units/cts.py", line 354, in parsable
    self.Text = CapitainsCtsText(resource=self.xml.getroot())
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/MyCapytain/resources/texts/local/capitains/cts.py", line 441, in __init__
    self.__findCRefPattern(self.resource)
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/MyCapytain/resources/texts/local/capitains/cts.py", line 452, in __findCRefPattern
    self.citation = Citation.ingest(resource=citation[0], xpath=".//tei:cRefPattern")
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/MyCapytain/common/reference.py", line 951, in ingest
    return resources[-1]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/HookTest/test.py", line 835, in cmd
    status = test.run()
  File "/home/thibault/dev/canonicals/digilibLT/venv/lib/python3.5/site-packages/HookTest/test.py", line 427, in run
    for future in executor.imap_unordered(self.unit, [file for file in self.text_files]):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
IndexError: list index out of range
```

I attach an example file to check this further later

Temp fix was 
```python
        if status is True:
[phi1257.phi001.digilibLT-lat1.txt](https://github.com/Capitains/HookTest/files/1958544/phi1257.phi001.digilibLT-lat1.txt)

            try:
                self.Text = CapitainsCtsText(resource=self.xml.getroot())
            except:
                status = False
                self.Text = None
```

See https://github.com/Capitains/MyCapytain/issues/162

**Comment by PonteIneptique** [comment]
Ok so my bad, actually this text only has `<refsDecl n="CTS"/>` which is what crashing HookTest and MyCapytain :)

**Comment by PonteIneptique** [comment]
Damn, we should have taken care of that in 2.0.7 as well.

**Comment by PonteIneptique** [comment]
Dealt currently in #125
